### ISSUE TITLE
Blackwell compatibility?

### ISSUE THREAD

**Issue by cymacyma** [JackismyShephard/ultimate-rvc#179]
Hi, I was a user of AICoverGen, but after upgrade my graphic card, everything was not working so I chose to move Ultimate RVC for better use and Python 3.12. But I still have a problem: It's not working simply.

Here's my environment:

OS: Windows 11 Home

GPU: NVIDIA RTX 5070 Ti 16GB

CUDA Toolkit version: 12.8

cuDNN version: 9.8.0

Installation of Ultimate RVC: PyPI package on Python 3.12

Error code:

> [~] Retrieving song...
[~] Separating vocals from instrumentals...
4.38kiB [00:00, 4.36MiB/s]
15.4kiB [00:00, 15.3MiB/s]
  0%|                                                                                           | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultimate_rvc\web\common.py", line 58, in _wrapped_fn
    res = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultimate_rvc\core\generate\song_cover.py", line 1031, in run_pipeline
    vocals_track, instrumentals_track = separate_audio(
                                        ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultimate_rvc\core\generate\song_cover.py", line 622, in separate_audio
    audio_separator.separate(
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\audio_separator\separator\separator.py", line 766, in separate
    output_files = self.model_instance.separate(audio_file_path, custom_output_names)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\audio_separator\separator\architectures\mdx_separator.py", line 158, in separate
    source = self.demix(mix)
             ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\audio_separator\separator\architectures\mdx_separator.py", line 379, in demix
    tar_waves = self.run_model(mix_wave, is_match_mix=is_match_mix)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\audio_separator\separator\architectures\mdx_separator.py", line 422, in run_model
    spek = self.stft(mix.to(self.torch_device))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\audio_separator\separator\uvr_lib_v5\stft.py", line 41, in __call__
    stft_output = torch.stft(reshaped_tensor, n_fft=self.n_fft, hop_length=self.hop_length, window=stft_window, center=True, return_complex=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\functional.py", line 707, in stft
    input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\functional.py", line 5209, in pad
    return torch._C._nn.pad(input, pad, mode, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\blocks.py", line 2137, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\blocks.py", line 1663, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\_backends\_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\utils.py", line 890, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultimate_rvc\web\common.py", line 65, in _wrapped_fn
    raise gr.Error(str(e)) from e
gradio.exceptions.Error: 'CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'

What should I do to fix this problem? Should I have to install CUDA Toolkit 12.1 for compatibility?

I'm not a developer but an end user, so I have not much knowledge about compatibility of CUDA. I also researched it as much as I can, what I found was there's no CUDA 12.8 support for PyTorch at this moment.

Thank you for your kind understanding.

**Comment by JackismyShephard** [comment]
@cymacyma as you mention CUDA 12.8 is not supported currently in pytorch and this project specifically uses cuda 12.4 (or below). Its hard for me to troubleshoot this issue as I am using 3080 myself. I expect you might have to wait until pytorch support cuda 12.8 and I upgrade the dependencies for this project.

**Comment by cymacyma** [comment]
@JackismyShephard Really thank you for your kind reply. I think I have to find any unstable option for Pytorch at this moment.

**Comment by cymacyma** [comment]
@JackismyShephard I just tested official version of PyTorch for CUDA 12.8, and it works perfect ㅇㅅㅇ/ I used PyPI package installation with

`pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu128`

Thank you for your effort and wonderful project!

**Comment by JackismyShephard** [comment]
@cymacyma Thank you for your kind words ! 

I am actually testing PyTorch 2.7.0 with CUDA 12.8 right now on Windows. So far everything seems to work. Once I have tested on linux and everything works I will push my changes including updates to the README. 

Feedback is always greatly appreciated (be it positive or negative). Sometimes its hard to see the forest for the trees when working solo on a project 😄
